version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-baileys-api
#    ports:
#      - "3000:3008"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    networks:
      - my-external-network
networks:
  my-external-network:
    external: true
